### ISSUE TITLE
Compile fail with missing symbol

### ISSUE THREAD

**Issue by brvier** [hypery2k/cordova-certificate-plugin#12]
/home/khertan/Projects/cordova-litewrite/platforms/android/src/de/martinreinhardt/cordova/plugins/CertificatesPlugin.java:101: error: cannot find symbol
                                LOG.e(LOG_TAG, "Got unkown error during setting webview in activity", e);
                                ^
  symbol: variable LOG
/home/khertan/Projects/cordova-litewrite/platforms/android/src/de/martinreinhardt/cordova/plugins/CertificatesPlugin.java:108: error: cannot find symbol
                LOG.e(LOG_TAG, "Got unkown error during passing to UI Thread", e);
                ^
  symbol:   variable LOG
  location: class CertificatesPlugin
2 errors

**Comment by brvier** [comment]
Duplicate of #11
Oups already fixed in github.

Npm isnt up to date.

**Comment by hypery2k** [comment]
New version is available: https://www.npmjs.com/package/cordova-plugin-certificates

**Comment by brvier** [comment]
thx
