### ISSUE TITLE
Causes Android App to Crash when installed

### ISSUE THREAD

**Issue by ghenry22** [hypery2k/cordova-certificate-plugin#19]
So this is a bit of an odd one but hopefully something that might be able to be addressed.  Applies to android only, iOS still works fine for me.

A few months back I noticed that when launching my android app I would intermittently get an error thrown up that says "The connection to the server was unsuccessful. (file:///android_asset/www/index.html)"

This is really weird because in every other way the app is loaded and working perfectly, no issues in the console, no errors anywhere.  With the most recent updates to the cordova system webview and I guess to the android cordova platform I started getting this every time the app started, making it unusable so actually had to put some time into troubleshooting this.

It was quite annoying to track down as there are no errors anywhere but I did find one other plugin that had encountered a similar error and when it was removed all worked as usual so I removed all plugins from my app and added them back one at a time, building and running after each.

As soon as this certificate plugin is added and trustunsecure(true) is called I immediately get the error on application start up causing the app to crash completely.

If I remove the certificate plugin and re-add all other plugins all works normally.  If I leave the plugin installed but do not call any functions on it in Android all is also ok.

I am thinking that this may be related to updates to the system webview.  Similarly the crosswalk fork of this plugin doesn't work with the latest versions of crosswalk so I figure if the system webview is also getting actively updated this may well be a similar issue.

This was a real pain to trace down and I definitely still need the ability to connect to sites with self signed (ie invalid) certificates so hopefully a fix can be found.  I am happy to provide any more info or explanation needed and help to test any potential fix.

**Comment by hypery2k** [comment]
maybe it has to do with the permissions

**Comment by ghenry22** [comment]
you mean android permissions?  any in particular you were thinking of?

Nothing has been required previously and I don't even know if there is a permission to allow insecure connections, I would guess not.

**Comment by hypery2k** [comment]
Was just a guess. Not sure. The whole webview handling on android regarding SSL really sucks. To be honest, I'm currently don't have really much time to investigate on this.

**Comment by JulienF22** [comment]
Hi, I got the same bug, solved by added  webView.stopLoading();  after  webView.clearCache(); in main execute

**Comment by freddyz** [comment]
@JulienF22 your fix worked to repair my problem!  I have created a pull request for this issue : https://github.com/hypery2k/cordova-certificate-plugin/pull/23

**Comment by hypery2k** [comment]
I've publish version 0.6.4
