### ISSUE TITLE
Can I use this plugin in Ionic 2 application?

### ISSUE THREAD

**Issue by Donbelar** [hypery2k/cordova-certificate-plugin#20]
I am going to create video player with Ionic 2 using html5 video tag.
The app is fine on web browser, but it does not run on android.
So I am going to use this plugin, but I don't know how to use this?
Please explain to use this plugin with Ionic 2.

**Comment by ghenry22** [comment]
You use it exactly the same way as in any other cordova project.

Add the plugin

Add the single line of code as in the readme on this repository.

Although - I have found that the current version of this plugin with an updated Android 6 or later now causes app crashes when enable certificates is called so your mileage may vary.

**Comment by hypery2k** [comment]
not sure if it's an issue with permissions
