### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by heymartinadams** [hypery2k/cordova-certificate-plugin#26]
Can you please explain what you mean by:
```cordova.plugins.certificates.trustUnsecureCerts(true)```

Do I put it into the `config.xml` file?

**Comment by escapedcat** [comment]
Looking at https://github.com/hypery2k/cordova-certificate-plugin/issues/3#issue-65774384 just within your JS code should work.

**Comment by heymartinadams** [comment]
Thank you, @escapedcat 🙏
