### ISSUE TITLE
how use in intel xdk

### ISSUE THREAD

**Issue by Novaboy63** [hypery2k/cordova-certificate-plugin#7]
where must use from this
cordova.plugins.certificates.trustUnsecureCerts(true)

on intel xdk
my code in intel xdk is this :

 <!DOCTYPE html>
<html>

<head>
    <title>test</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">

<style type="text/css">
html, body {
  overflow: hidden;
}
</style>

```
<meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=no">

<script src="cordova.js" id="xdkJScordova_"></script>

<script src="js/app.js"></script>           <!-- for your event code, see README and file comments for details -->
<script src="js/init-app.js"></script>      <!-- for your init code, see README and file comments for details -->
<script src="xdk/init-dev.js"></script>     <!-- normalizes device and document ready events, see file for details -->
       <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        ;(function($){
            $(document).ready(function(){
                $('iframe').height( $(window).height() );
                $(window).resize(function(){
                    $('iframe').height( $(this).height() );
                });
            });
        })(jQuery);
    </script>
```

</head>

<body>
   <iframe   width="100%" src="https://www.bmi.ir" scrolling="yes" frameborder="0" height="100%">
</iframe>

</body>
</html>

**Comment by escapedcat** [comment]
Have a look at the [Example for the onDeviceReady Event](http://cordova.apache.org/docs/en/edge/cordova_events_events.md.html#Events).
Also in [this issue](https://github.com/hypery2k/cordova-certificate-plugin/issues/3) you see an example on how to use it.
