### ISSUE TITLE
So what for Cordova 5.1.1 build Android?

### ISSUE THREAD

**Issue by xale76** [hypery2k/cordova-certificate-plugin#8]
Still got errors. Any solution? I develop with Intel XDK (no crosswalk). ios works fine, Android build fails. Should I refer to other version? I see that only 0.5.0 is available.
please help me

**Comment by hypery2k** [comment]
the problem is that supporting Cordova 5.x breaks compatibility with cordova 4.x

**Comment by xale76** [comment]
So it is not usable in android 5?
Il 06/Ott/2015 23:15, "Martin Reinhardt" notifications@github.com ha
scritto:

**Comment by hypery2k** [comment]
Currently not, I have to update the sources to the latest cordova API

**Comment by xale76** [comment]
Ok but I hope that You will do this shortly...I need it! Thank You
Il 07/Ott/2015 07:18, "Martin Reinhardt" notifications@github.com ha
scritto:

**Comment by ToKaDev** [comment]
+1

**Comment by hypery2k** [comment]
duplicate of #6

**Comment by xale76** [comment]
what?

2015-10-07 12:45 GMT+02:00 ToKaDev notifications@github.com:

**Comment by hypery2k** [comment]
the error is the same as discussed in #6 
So no need for differentiate it here. I try to fix it
